routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::post('users/update/all', 'UsersController@updateAll');
Route::resource('/users', 'UsersController', ['only' => ['index', 'create', 'store', 'edit', 'update']]);
Route::get('/lastame/search', 'UsersController@searchLastname');
Route::get('/date/search', 'UsersController@searchDate');

Route::resource('/books', 'BooksController', ['only' => ['index']]);





//Route::post('/store/soap', 'SoapController@create');
Route::any('/soap/server', 'SoapServerController@index');
Route::resource('/books', 'BooksController',
                ['only' => ['index']]);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'birthdate', 'company', 'user_type_id',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function user_type(){
      return $this->hasOne('App\UserType', 'id', 'user_type_id')->with('role');
    }

    public function role(){
      return $this->belongsToMany('App\Rolle', 'user__roles')->with('type');
    }

    static function created_at($date){
      $datemonth = ['01' => 'января', '02' => 'февраля', '03' => 'марта',
      '04' => 'апреля', '05' => 'мая', '06' => 'июня', '07' => 'июля', '08' => 'августа',
      '09' => 'сентября', '10' => 'октября', '11' => 'ноября', '12' => 'декабря'];
      $month = date("m", strtotime($date));
      $day = date("d", strtotime($date));
      $year = date("Y", strtotime($date));
      $hour = date("H", strtotime($date));
      $min = date("i", strtotime($date));
      return $day.' '.$datemonth[$month].' '.$year.' '. $hour.':'.$min;
    }

}

app/UserType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserType extends Model
{
  public function role(){
    return $this->hasMany('App\Rolle');
  }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use App\Rolle;
use App\User_Role;
use App\Client;
use App\Http\Requests\SoapRequest;
class UsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $users = User::with('user_type')->with('role')->paginate(10);
        return view('users.index', compact('users', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $roles = Rolle::all();
      return view('users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(SoapRequest $request)
    {
      $new = $request->all();
      $new = array('create' => $new);
      $client = new Client;
      $client->create($new);
      return redirect('/users');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $users = User::with('user_type')->with('role')->findOrFail($user)[0];
        return view('users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(SoapRequest $request, User $user)
    {

        $user_id = array('id' => $user->id);
        $old = $request->all();
        $old = array_merge($user_id,$old);
        $old = array('update' => $old);
        $client = new Client;
        $client->update($old);
        return redirect('/users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }
    public function updateAll(Request $request){
      $ckecked = $request->all();
      User_Role::whereIn('user_id',$ckecked['user_id'])->delete();
      foreach ($ckecked['UserRole'] as $user => $keys) {
        foreach ($keys as $key => $value) {
          User_Role::insert(['user_id' => $user, 'rolle_id' => $key]);
        }
      }
      return redirect()->back();
    }
    public function searchLastname(Request $request){
      $name = $request->name;
      $users = User::with('role')->where('name', $name)->paginate(10);
      $roles = Rolle::all();
      return view('users.index', compact('users', 'roles'));
    }

    public function searchDate(Request $request){
      $created_from = date("Y-m-d", strtotime($request->created_from));
      $created_to = date("Y-m-d", strtotime($request->created_to));
      $users = User::with('role')
      ->whereBetween('created_at',[$created_from, $created_to])
      ->paginate(10);
      $roles = Rolle::all();
      return view('users.index', compact('users', 'roles'));
    }
}

resources/views/users/create.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/public/css/app.css">
        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

</head>

<body>
  <div class="content" style="margin:20px;">
    @if($errors->any())
    <div class="alert alert-danger" role="alert">
  {{ $errors->first() }}
    </div>
    @endif
    <form action="{{route('users.store')}}" method="post">
      {{csrf_field()}}
      <h2>Создание пользователя</h2>
      <div class="form-group">
        <label for="name">Имя</label>
        <input type="text" name="name" class="form-control" id="name" aria-describedby="name" placeholder="Введи имя" required>
        <small id="name" class="form-text text-muted">Сюда напишите имя</small>
      </div>

      <div class="form-group">
        <label for="birthdate">Дата рождения</label>
        <input type="date" name="birthdate" class="form-control" id="birthdate" aria-describedby="birthdate" placeholder="д.м.г">
        <small id="birthdate" class="form-text text-muted">Здесь дата рождения</small>
      </div>

      <div class="form-group">
        <label for="company">Организация</label>
        <input type="text" name="company" class="form-control" id="company" aria-describedby="comany" placeholder="Введи название организации" required>
        <small id="comany" class="form-text text-muted">Название организации</small>
      </div>

      <div class="form-group">
        <label for="UserType">Тип пользователя</label>
        <select type="text" name="user_type_id" class="form-control" id="UserType" aria-describedby="UserType" placeholder="Введи имя" required>
          <option value="1">Гражданин</option>
          <option value="2">Управляющая компания</option>
          <option value="3">Администрация района</option>
        </select>
        <small id="UserType" class="form-text text-muted">Название организации</small>
      </div>

      <div class="form-group">
        <label for="role1">Личный кабинет</label>
        <input type="checkbox" name="role[1]" id="role1">
        <label for="role2">Сообщения</label>
        <input type="checkbox" name="role[2]" id="role2">
        <label for="role3">Отчеты</label>
        <input type="checkbox" name="role[3]" id="role3">
        <label for="role4">Раскрытие информации</label>
        <input type="checkbox" name="role[4]" id="role4">
        <label for="role5">Сообщения</label>
        <input type="checkbox" name="role[5]" id="role5">
      </div>
      <button type="submit" name="button" class="btn btn-primary">Сохранить</button>
    </form>
  </div>
</body>
</html>

resources/views/users/edit.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/public/css/app.css">
        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

</head>

<body>
  <div class="content" style="margin:20px;">
    @if($errors->any())
    <div class="alert alert-danger" role="alert">
  {{ $errors->first() }}
    </div>
    @endif

    <form action="{{route('users.update', $user->id)}}" method="post">
      {{csrf_field()}}
      <input type="hidden" name="_method" value="PATCH">
      <h2>Обновление пользователя</h2>
      <div class="form-group">
        <label for="name">Имя</label>
        <input type="text" name="name" class="form-control" id="name" value="{{$user->name}}" aria-describedby="name" placeholder="Введи имя" required>
        <small id="name" class="form-text text-muted">Сюда напишите имя</small>
      </div>

      <div class="form-group">
        <label for="birthdate">Дата рождения</label>
        <input type="date" name="birthdate" class="form-control" id="birthdate" value="{{$user->birthdate or ''}}" aria-describedby="birthdate" placeholder="д.м.г">
        <small id="birthdate" class="form-text text-muted">Здесь дата рождения</small>
      </div>

      <div class="form-group">
        <label for="company">Организация</label>
        <input type="text" name="company" class="form-control" id="company" value="{{$user->company}}" aria-describedby="comany" placeholder="Введи название организации" required>
        <small id="comany" class="form-text text-muted">Название организации</small>
      </div>
      <div class="form-group">
        <label for="UserType">Тип пользователя</label>
        <select type="text" name="UserType" class="form-control" id="UserType" aria-describedby="UserType" placeholder="Введи имя" required>
          <option value="1" @if($user->user_type->id == 1) selected @endif>Гражданин</option>
          <option value="2" @if($user->user_type->id == 2) selected @endif>Управляющая компания</option>
          <option value="3" @if($user->user_type->id == 3) selected @endif>Администрация района</option>
        </select>
        <small id="UserType" class="form-text text-muted">Название организации</small>
      </div>

      <div class="form-group">
        @php
        if(isset($i)){

        }
        else{
          $i=1;
        }
        @endphp
        <ul>
        @forelse($user->user_type->role as $rol)
        <li>
          <label for="exampleInputEmail{{$i}}">{{$rol->title}}</label>
          <input type="checkbox" name="role[{{$rol->id}}]" id="exampleInputEmail{{$i}}" @foreach($user->role as $role) @if($role->id == $rol->id) checked @endif @endforeach >
        </li>
        @php
        $i++;
        @endphp
        @empty
        @endforelse
      </div>
      <button type="submit" name="button" class="btn btn-primary">Сохранить</button>
    </form>
  </div>
</body>
</html>

resources/views/users/index.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="/public/css/app.css">
        <title>Laravel</title>

        <!-- Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

</head>

<body>
<div class="content" style="margin:20px;">
  <a href="/users/create" class="btn btn-primary">Создать</a><br>
  <form action="/lastame/search" method="get">
    <input type="text" name="name" placeholder="Фамилия">
  </form>
<br>
  <form action="/date/search" method="get">
    <input type="text" name="created_from" placeholder="Дата создания с">-
    <input type="text" name="created_to" placeholder="Дата создания по">
    <input type="submit"  value="Фильтровать">
  </form>


  <form action="/users/update/all" method="post">
    {{csrf_field()}}

  <table class="table">
    <thead>
      <tr>
        <th>ФИО</th>
        <th>Время создания</th>
        <th>Тип пользователя</th>
        <th>Роли</th>
        <th>Действия</th>
      </tr>
    </thead>
    <tbody>
      @forelse($users as $user)
      <input type="hidden" name="user_id[]" value="{{$user->id}}">
      <tr>
        <td>{{$user->name or 'Неизвестно'}}</td>
        <td>{{User::created_at($user->created_at)}}</td>
        <td>{{$user->user_type->title}}</td>
          <td>
            @php
            if(isset($i)){

            }
            else{
              $i=1;
            }
            @endphp
            <ul>
            @forelse($user->user_type->role as $rol)
            <li>
              <label for="exampleInputEmail{{$i}}">{{$rol->title}}</label>
              <input type="checkbox" name="UserRole[{{$user->id}}][{{$rol->id}}]role[]" id="exampleInputEmail{{$i}}" @foreach($user->role as $role) @if($role->id == $rol->id) checked @endif @endforeach >
            </li>
            @php
            $i++;
            @endphp
            @empty
            @endforelse
            </ul>
          </td>
        <td>
          <a href="{{route('users.edit', $user->id)}}" class="btn btn-success">Изменить</a>
          <button type="button" name="button" class="btn btn-danger">Удалить</button>
        </td>
      </tr>
      @empty
      @endforelse
      <tr>
        <td>
          <button type="sumbit" class="btn btn-primary" name="button">Сохранить</button>
        </td>
      </tr>
    </tbody>
  </table>
  </form>
  {{$users->links()}}
</div>
</body>
</html>